/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MainImportDealBody model module.
 * @module model/MainImportDealBody
 * @version 1.0.0
 */
class MainImportDealBody {
    /**
     * Constructs a new <code>MainImportDealBody</code>.
     * @alias module:model/MainImportDealBody
     */
    constructor() { 
        
        MainImportDealBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MainImportDealBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MainImportDealBody} obj Optional instance to populate.
     * @return {module:model/MainImportDealBody} The populated <code>MainImportDealBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MainImportDealBody();

            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('collectionPath')) {
                obj['collectionPath'] = ApiClient.convertToType(data['collectionPath'], 'String');
            }
            if (data.hasOwnProperty('dealIDs')) {
                obj['dealIDs'] = ApiClient.convertToType(data['dealIDs'], ['Number']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} collection
 */
MainImportDealBody.prototype['collection'] = undefined;

/**
 * @member {String} collectionPath
 */
MainImportDealBody.prototype['collectionPath'] = undefined;

/**
 * @member {Array.<Number>} dealIDs
 */
MainImportDealBody.prototype['dealIDs'] = undefined;

/**
 * @member {String} name
 */
MainImportDealBody.prototype['name'] = undefined;






export default MainImportDealBody;

