/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MainCreateCollectionBody model module.
 * @module model/MainCreateCollectionBody
 * @version 1.0.0
 */
class MainCreateCollectionBody {
    /**
     * Constructs a new <code>MainCreateCollectionBody</code>.
     * @alias module:model/MainCreateCollectionBody
     */
    constructor() { 
        
        MainCreateCollectionBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MainCreateCollectionBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MainCreateCollectionBody} obj Optional instance to populate.
     * @return {module:model/MainCreateCollectionBody} The populated <code>MainCreateCollectionBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MainCreateCollectionBody();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
MainCreateCollectionBody.prototype['description'] = undefined;

/**
 * @member {String} name
 */
MainCreateCollectionBody.prototype['name'] = undefined;






export default MainCreateCollectionBody;

