/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MainAddContentToCollectionParams model module.
 * @module model/MainAddContentToCollectionParams
 * @version 1.0.0
 */
class MainAddContentToCollectionParams {
    /**
     * Constructs a new <code>MainAddContentToCollectionParams</code>.
     * @alias module:model/MainAddContentToCollectionParams
     */
    constructor() { 
        
        MainAddContentToCollectionParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MainAddContentToCollectionParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MainAddContentToCollectionParams} obj Optional instance to populate.
     * @return {module:model/MainAddContentToCollectionParams} The populated <code>MainAddContentToCollectionParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MainAddContentToCollectionParams();

            if (data.hasOwnProperty('cids')) {
                obj['cids'] = ApiClient.convertToType(data['cids'], ['String']);
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
            if (data.hasOwnProperty('contents')) {
                obj['contents'] = ApiClient.convertToType(data['contents'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} cids
 */
MainAddContentToCollectionParams.prototype['cids'] = undefined;

/**
 * @member {String} collection
 */
MainAddContentToCollectionParams.prototype['collection'] = undefined;

/**
 * @member {Array.<Number>} contents
 */
MainAddContentToCollectionParams.prototype['contents'] = undefined;






export default MainAddContentToCollectionParams;

