/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MainUserStatsResponse model module.
 * @module model/MainUserStatsResponse
 * @version 1.0.0
 */
class MainUserStatsResponse {
    /**
     * Constructs a new <code>MainUserStatsResponse</code>.
     * @alias module:model/MainUserStatsResponse
     */
    constructor() { 
        
        MainUserStatsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MainUserStatsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MainUserStatsResponse} obj Optional instance to populate.
     * @return {module:model/MainUserStatsResponse} The populated <code>MainUserStatsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MainUserStatsResponse();

            if (data.hasOwnProperty('numPins')) {
                obj['numPins'] = ApiClient.convertToType(data['numPins'], 'Number');
            }
            if (data.hasOwnProperty('totalSize')) {
                obj['totalSize'] = ApiClient.convertToType(data['totalSize'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} numPins
 */
MainUserStatsResponse.prototype['numPins'] = undefined;

/**
 * @member {Number} totalSize
 */
MainUserStatsResponse.prototype['totalSize'] = undefined;






export default MainUserStatsResponse;

