/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MainCollection model module.
 * @module model/MainCollection
 * @version 1.0.0
 */
class MainCollection {
    /**
     * Constructs a new <code>MainCollection</code>.
     * @alias module:model/MainCollection
     */
    constructor() { 
        
        MainCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MainCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MainCollection} obj Optional instance to populate.
     * @return {module:model/MainCollection} The populated <code>MainCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MainCollection();

            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'Number');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} createdAt
 */
MainCollection.prototype['createdAt'] = undefined;

/**
 * @member {String} description
 */
MainCollection.prototype['description'] = undefined;

/**
 * @member {String} name
 */
MainCollection.prototype['name'] = undefined;

/**
 * @member {Number} userId
 */
MainCollection.prototype['userId'] = undefined;

/**
 * @member {String} uuid
 */
MainCollection.prototype['uuid'] = undefined;






export default MainCollection;

