/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MainGetApiKeysResp model module.
 * @module model/MainGetApiKeysResp
 * @version 1.0.0
 */
class MainGetApiKeysResp {
    /**
     * Constructs a new <code>MainGetApiKeysResp</code>.
     * @alias module:model/MainGetApiKeysResp
     */
    constructor() { 
        
        MainGetApiKeysResp.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MainGetApiKeysResp</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MainGetApiKeysResp} obj Optional instance to populate.
     * @return {module:model/MainGetApiKeysResp} The populated <code>MainGetApiKeysResp</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MainGetApiKeysResp();

            if (data.hasOwnProperty('expiry')) {
                obj['expiry'] = ApiClient.convertToType(data['expiry'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} expiry
 */
MainGetApiKeysResp.prototype['expiry'] = undefined;

/**
 * @member {String} token
 */
MainGetApiKeysResp.prototype['token'] = undefined;






export default MainGetApiKeysResp;

