/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UtilHttpError model module.
 * @module model/UtilHttpError
 * @version 1.0.0
 */
class UtilHttpError {
    /**
     * Constructs a new <code>UtilHttpError</code>.
     * @alias module:model/UtilHttpError
     */
    constructor() { 
        
        UtilHttpError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UtilHttpError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UtilHttpError} obj Optional instance to populate.
     * @return {module:model/UtilHttpError} The populated <code>UtilHttpError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UtilHttpError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} code
 */
UtilHttpError.prototype['code'] = undefined;

/**
 * @member {String} details
 */
UtilHttpError.prototype['details'] = undefined;

/**
 * @member {String} message
 */
UtilHttpError.prototype['message'] = undefined;






export default UtilHttpError;

