/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EstuaryApi);
  }
}(this, function(expect, EstuaryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EstuaryApi.MainEstimateDealBody();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MainEstimateDealBody', function() {
    it('should create an instance of MainEstimateDealBody', function() {
      // uncomment below and update the code to test MainEstimateDealBody
      //var instance = new EstuaryApi.MainEstimateDealBody();
      //expect(instance).to.be.a(EstuaryApi.MainEstimateDealBody);
    });

    it('should have the property durationBlks (base name: "durationBlks")', function() {
      // uncomment below and update the code to test the property durationBlks
      //var instance = new EstuaryApi.MainEstimateDealBody();
      //expect(instance).to.be();
    });

    it('should have the property replication (base name: "replication")', function() {
      // uncomment below and update the code to test the property replication
      //var instance = new EstuaryApi.MainEstimateDealBody();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new EstuaryApi.MainEstimateDealBody();
      //expect(instance).to.be();
    });

    it('should have the property verified (base name: "verified")', function() {
      // uncomment below and update the code to test the property verified
      //var instance = new EstuaryApi.MainEstimateDealBody();
      //expect(instance).to.be();
    });

  });

}));
