/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import MainAddContentToCollectionParams from './model/MainAddContentToCollectionParams';
import MainCollection from './model/MainCollection';
import MainCreateCollectionBody from './model/MainCreateCollectionBody';
import MainEstimateDealBody from './model/MainEstimateDealBody';
import MainGetApiKeysResp from './model/MainGetApiKeysResp';
import MainImportDealBody from './model/MainImportDealBody';
import MainUserStatsResponse from './model/MainUserStatsResponse';
import UtilContentAddIpfsBody from './model/UtilContentAddIpfsBody';
import UtilHttpError from './model/UtilHttpError';
import CollectionsApi from './api/CollectionsApi';
import ContentApi from './api/ContentApi';
import DealsApi from './api/DealsApi';
import MetricsApi from './api/MetricsApi';
import MinerApi from './api/MinerApi';
import NetApi from './api/NetApi';
import PinningApi from './api/PinningApi';
import PublicApi from './api/PublicApi';
import UserApi from './api/UserApi';


/**
* This_is_the_API_for_the_Estuary_application_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EstuaryApi = require('index'); // See note below*.
* var xxxSvc = new EstuaryApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EstuaryApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EstuaryApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EstuaryApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The MainAddContentToCollectionParams model constructor.
     * @property {module:model/MainAddContentToCollectionParams}
     */
    MainAddContentToCollectionParams,

    /**
     * The MainCollection model constructor.
     * @property {module:model/MainCollection}
     */
    MainCollection,

    /**
     * The MainCreateCollectionBody model constructor.
     * @property {module:model/MainCreateCollectionBody}
     */
    MainCreateCollectionBody,

    /**
     * The MainEstimateDealBody model constructor.
     * @property {module:model/MainEstimateDealBody}
     */
    MainEstimateDealBody,

    /**
     * The MainGetApiKeysResp model constructor.
     * @property {module:model/MainGetApiKeysResp}
     */
    MainGetApiKeysResp,

    /**
     * The MainImportDealBody model constructor.
     * @property {module:model/MainImportDealBody}
     */
    MainImportDealBody,

    /**
     * The MainUserStatsResponse model constructor.
     * @property {module:model/MainUserStatsResponse}
     */
    MainUserStatsResponse,

    /**
     * The UtilContentAddIpfsBody model constructor.
     * @property {module:model/UtilContentAddIpfsBody}
     */
    UtilContentAddIpfsBody,

    /**
     * The UtilHttpError model constructor.
     * @property {module:model/UtilHttpError}
     */
    UtilHttpError,

    /**
    * The CollectionsApi service constructor.
    * @property {module:api/CollectionsApi}
    */
    CollectionsApi,

    /**
    * The ContentApi service constructor.
    * @property {module:api/ContentApi}
    */
    ContentApi,

    /**
    * The DealsApi service constructor.
    * @property {module:api/DealsApi}
    */
    DealsApi,

    /**
    * The MetricsApi service constructor.
    * @property {module:api/MetricsApi}
    */
    MetricsApi,

    /**
    * The MinerApi service constructor.
    * @property {module:api/MinerApi}
    */
    MinerApi,

    /**
    * The NetApi service constructor.
    * @property {module:api/NetApi}
    */
    NetApi,

    /**
    * The PinningApi service constructor.
    * @property {module:api/PinningApi}
    */
    PinningApi,

    /**
    * The PublicApi service constructor.
    * @property {module:api/PublicApi}
    */
    PublicApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
