/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EstuaryApi);
  }
}(this, function(expect, EstuaryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EstuaryApi.CollectionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CollectionsApi', function() {
    describe('collectionsAddContentPost', function() {
      it('should call collectionsAddContentPost successfully', function(done) {
        //uncomment below and update the code to test collectionsAddContentPost
        //instance.collectionsAddContentPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectionsContentColuuidGet', function() {
      it('should call collectionsContentColuuidGet successfully', function(done) {
        //uncomment below and update the code to test collectionsContentColuuidGet
        //instance.collectionsContentColuuidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectionsCreatePost', function() {
      it('should call collectionsCreatePost successfully', function(done) {
        //uncomment below and update the code to test collectionsCreatePost
        //instance.collectionsCreatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectionsFsAddPost', function() {
      it('should call collectionsFsAddPost successfully', function(done) {
        //uncomment below and update the code to test collectionsFsAddPost
        //instance.collectionsFsAddPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectionsFsListGet', function() {
      it('should call collectionsFsListGet successfully', function(done) {
        //uncomment below and update the code to test collectionsFsListGet
        //instance.collectionsFsListGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('collectionsListGet', function() {
      it('should call collectionsListGet successfully', function(done) {
        //uncomment below and update the code to test collectionsListGet
        //instance.collectionsListGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
