/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EstuaryApi);
  }
}(this, function(expect, EstuaryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EstuaryApi.ContentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContentApi', function() {
    describe('contentAddCarPost', function() {
      it('should call contentAddCarPost successfully', function(done) {
        //uncomment below and update the code to test contentAddCarPost
        //instance.contentAddCarPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentAddIpfsPost', function() {
      it('should call contentAddIpfsPost successfully', function(done) {
        //uncomment below and update the code to test contentAddIpfsPost
        //instance.contentAddIpfsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentAddPost', function() {
      it('should call contentAddPost successfully', function(done) {
        //uncomment below and update the code to test contentAddPost
        //instance.contentAddPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentAggregatedContentGet', function() {
      it('should call contentAggregatedContentGet successfully', function(done) {
        //uncomment below and update the code to test contentAggregatedContentGet
        //instance.contentAggregatedContentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentAllDealsGet', function() {
      it('should call contentAllDealsGet successfully', function(done) {
        //uncomment below and update the code to test contentAllDealsGet
        //instance.contentAllDealsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentBwUsageContentGet', function() {
      it('should call contentBwUsageContentGet successfully', function(done) {
        //uncomment below and update the code to test contentBwUsageContentGet
        //instance.contentBwUsageContentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentCreatePost', function() {
      it('should call contentCreatePost successfully', function(done) {
        //uncomment below and update the code to test contentCreatePost
        //instance.contentCreatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentDealsGet', function() {
      it('should call contentDealsGet successfully', function(done) {
        //uncomment below and update the code to test contentDealsGet
        //instance.contentDealsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentEnsureReplicationDatacidGet', function() {
      it('should call contentEnsureReplicationDatacidGet successfully', function(done) {
        //uncomment below and update the code to test contentEnsureReplicationDatacidGet
        //instance.contentEnsureReplicationDatacidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentFailuresContentGet', function() {
      it('should call contentFailuresContentGet successfully', function(done) {
        //uncomment below and update the code to test contentFailuresContentGet
        //instance.contentFailuresContentGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentImportdealPost', function() {
      it('should call contentImportdealPost successfully', function(done) {
        //uncomment below and update the code to test contentImportdealPost
        //instance.contentImportdealPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentListGet', function() {
      it('should call contentListGet successfully', function(done) {
        //uncomment below and update the code to test contentListGet
        //instance.contentListGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentReadContGet', function() {
      it('should call contentReadContGet successfully', function(done) {
        //uncomment below and update the code to test contentReadContGet
        //instance.contentReadContGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentStagingZonesGet', function() {
      it('should call contentStagingZonesGet successfully', function(done) {
        //uncomment below and update the code to test contentStagingZonesGet
        //instance.contentStagingZonesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentStatsGet', function() {
      it('should call contentStatsGet successfully', function(done) {
        //uncomment below and update the code to test contentStatsGet
        //instance.contentStatsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentStatusIdGet', function() {
      it('should call contentStatusIdGet successfully', function(done) {
        //uncomment below and update the code to test contentStatusIdGet
        //instance.contentStatusIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
