/**
 * Estuary API
 * This is the API for the Estuary application.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EstuaryApi);
  }
}(this, function(expect, EstuaryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EstuaryApi.PinningApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PinningApi', function() {
    describe('pinningPinsGet', function() {
      it('should call pinningPinsGet successfully', function(done) {
        //uncomment below and update the code to test pinningPinsGet
        //instance.pinningPinsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pinningPinsPost', function() {
      it('should call pinningPinsPost successfully', function(done) {
        //uncomment below and update the code to test pinningPinsPost
        //instance.pinningPinsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pinningPinsRequestidDelete', function() {
      it('should call pinningPinsRequestidDelete successfully', function(done) {
        //uncomment below and update the code to test pinningPinsRequestidDelete
        //instance.pinningPinsRequestidDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pinningPinsRequestidGet', function() {
      it('should call pinningPinsRequestidGet successfully', function(done) {
        //uncomment below and update the code to test pinningPinsRequestidGet
        //instance.pinningPinsRequestidGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pinningPinsRequestidPost', function() {
      it('should call pinningPinsRequestidPost successfully', function(done) {
        //uncomment below and update the code to test pinningPinsRequestidPost
        //instance.pinningPinsRequestidPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
